### ISSUE TITLE
Nep5资产缺失

### ISSUE THREAD

**Issue by liyaojian** [NeoNextClub/squirrel#1]
例如：交易0xb4eb2dc35226e6520ee4e09a56197dff91547b50a7f57edc82930fc18c75dffc，此[资产NNC](https://neotracker.io/asset/fc732edee1efdf968c23c20a9628eaa5a6ccb934)解析报错，没有入库。

**Comment by hactrox** [comment]
你好，如果运行过程中报错，请将错误栈贴出以便于确定问题来源。
关于 NNC 资产(scrpitHash=fc732edee1efdf968c23c20a9628eaa5a6ccb934)，此资产在注册或合约升级时未使用 Neo 标准方法
